remote_theme: daattali/beautiful-jekyll@6.0.1
title: Biomedical Stuff and more!
author: Raúl Verea Reina

###############################################
# --- List of links in the navigation bar --- #
###############################################

# For each link, make sure to create a corresponding markdown file in the root folder (like `aboutme.md`)

navbar-links:
  About Me: "aboutme"
  Tag Index: "tags-index"  # Agrega aquí tu nueva página


################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/iop.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "raul.verea@estudiants.urv.cat"
  github: https://github.com/RaulVerea
  linkedin: https://www.linkedin.com/in/raul-verea-reina/
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  github: true
  facebook: false
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "raulverea.github.io"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#F4F4F4"  # Suave tono neutro de fondo
text-col: "#333333"  # Color de texto oscuro para buena legibilidad
link-col: "#0066CC"  # Azul profesional y llamativo para enlaces
hover-col: "#004C99"  # Azul más oscuro para el hover, para dar interacción
navbar-col: "#2C3E50"  # Un gris oscuro para el fondo de la barra de navegación
navbar-text-col: "#FFFFFF"  # Blanco para el texto en la barra de navegación
navbar-border-col: "#BDC3C7"  # Gris suave para el borde de la barra de navegación
footer-col: "#34495E"  # Gris oscuro para el fondo del pie de página
footer-text-col: "#ECF0F1"  # Texto claro en el pie de página para buena legibilidad
footer-link-col: "#3498DB"  # Azul para los enlaces en el pie de página
footer-hover-col: "#1ABC9C"  # Verde suave para el hover de los enlaces en el pie de página


# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

navbar-img: "/images/header.jpg"
footer-img: "/images/footer.jpg"
#page-img: "/assets/img/bgimage.png"


################
# --- Misc --- #
################

# Date Format to show dates of posts
date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
